### ISSUE TITLE
Main page should clearly communicate core use-cases, including easy acquisition of data

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad.org#10]
I think the paragraf "What is datalad?" should mentioning something like "An app store for data" or "packaging like software" or "Install data like it was software", .... some catchy phrase along those lines. Even people who have no idea what version control is, get to recognize a convenient feature right in the first paragraf that way.

**Comment by aqw** [comment]
@bpoldrack Yarik and Michael had a convo yesterday where they identified three clear use cases, and your suggested case is among them.

Currently, effort are underway to muddy that clarity, but I have hope sanity will prevail. ;-)

The current state of the new site was built around a lack of content or clarity of message. Now that we have that, the flow will change, but it will take some time.

---Alex

**Comment by bpoldrack** [comment]
Sure - no offense here. Just wanted to make it an issue right away so we don't forget about it.

**Comment by aqw** [comment]
Reopening and retitling the issue, as @mih informed me it is common in datalad culture to leave issues open until they're resolved.

**Comment by aqw** [comment]
@bpoldrack Do you feel the latest incarnation of main page on the dev server resolves this?

**Comment by aqw** [comment]
I'm going to close this, as I feel it has been resolved. @bpoldrack If you feel otherwise, please reopen and we can discuss. :-)

---Alex
