### ISSUE TITLE
Website update removed the "made with datalad" badge

### ISSUE THREAD

**Issue by mih** [datalad/datalad.org#102]
Was available at `badges/made_with.svg`.

This broke all default READMEs on github

![image](https://user-images.githubusercontent.com/136479/145010851-3a55da8c-a8e1-4929-8e1d-5cb8304cf23d.png)

**Comment by aqw** [comment]
Restored. Should be good now. I also converted the badge's text to paths, so it'll render the same everywhere, and minified it (82a66974803b4c8b56652d739d23cd5a471c8c12).

**Comment by mih** [comment]
Confirmed working ... and looking good! Thx!

**Comment by aqw** [comment]
Yeah; there was a windows where an oversized badge was rendered. That has been fixed in 055cdda. Everything should be good now.
