### ISSUE TITLE
Please let me know upfront when rewriting history

### ISSUE THREAD

**Issue by adswa** [datalad/datalad.org#104]
Thanks to a monthly link-checker, I realized that there is one old ascii-cast script that a chapter in the datalad handbook relies on. While it doesn't exist anymore, it is still available in this repository's past versions. I currently access it at https://raw.githubusercontent.com/datalad/datalad.org/7e8e39b1f08d0a54ab521586f27ee918b4441d69/content/asciicast/seamless_nested_repos.sh. Its certainly suboptimal to still include it in the handbook, but it fits the narrative and keeps working for now. However, if you (ping @aqw, @jsheunis, @mih) plan to rewrite history at some point please let me know such that I can adjust the handbook. :)

**Comment by aqw** [comment]
It wasn't so much rewriting history as much as it was deleting stuff that was perceived to be unused. ;-)

I can restore the file if you'd like. :-)

**Comment by adswa** [comment]
I don't think that is necessary, everything works as is now :) Thanks for asking!
(also closing this, just wanted to open it as FYI)
