### ISSUE TITLE
Recover `copyright.html` for website, possibly reuse for artwork

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad.org#107]
https://www.datalad.org/copyright.html

**Comment by jsheunis** [comment]
The rst source of the copyright page previously hosted on datalad.org:

https://github.com/datalad/datalad.org/blob/6d137bed7e5ca479505c2088a96f2f0c82aa8ae0/content/pages/copyright.rst

@aqw  Do you think it's fine to assign copyright to "DataLad developers" as opposed to individuals, or is there a better reason for using the latter?

**Comment by aqw** [comment]
Well, some things are not done by DataLad developers, so in those cases, individuals make sense. ;-)

In general, copyright assignment belongs to those who did the work (usually individuals) unless it's been transferred to an organization (and "DataLad Developers" is not an entity).

That being said... it's become common to use a broad "catch all" for project copyright (such as "DataLad Developers") with the expectation that the specific authorship requires inspection of the version control history.

My take-away: "DataLad Developers" is fine to use when version control is in place, and when it is indeed accurate. Assets of external origin are used on the site, and should not be ascribed to DataLad Developers.

**Comment by aqw** [comment]
Small nit: I noticed an oops of mine in the site HTML:

```
<link rel="license" hreflang="en" href="copyright.html" />
```

The `copyright.html` should probably be changed to `/copyright.html`, so that it is accurate regardless where one is in the hierarchy.

**Comment by jsheunis** [comment]
Ok ok, I should have known that a detailed approach is more accurate than my lazy catch all suggestion 😄  Thanks for the suggestions. I will investigate if the version control is indeed in place for all, I suspect not. Will add specific names as far as I am able to, and will request some input to make things more accurate and the PR is done.
