### ISSUE TITLE
Data handles?

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad.org#11]
In the second paragraf of "What is datalad?" we are currently reintroducing the term "data handle". I have no strong opinion on that term, but is this intentional? As far as I'm aware we didn't use it in any recent doc.

**Comment by aqw** [comment]
@bpoldrack I used the term. There was no intent other than to communicate what a data handle is. The content is very much in flux. If you have a problem with it, please suggest language that is a clear win over it.

---Alex

**Comment by mih** [comment]
It is true that we stopped using that. However, when reading it again, I found that in this particular place it is more useful than "dataset" to convey the idea that our datasets are not the same as a tarball -- without going down the rabbit hole of explanation. Just the right vibes....

**Comment by aqw** [comment]
@mih I was using "data handle" in the sense that a given file can be transparently acquired over a myriad of different protocols and mirrors. Not sure what else to call is, because I find the term "special remote" to be uninformative.

---Alex

**Comment by bpoldrack** [comment]
Well, that's a good point, @mih.
I don't really have a problem with the term, Alex. I just wondered whether we introduce confusion here, if we don't use it elsewhere anymore.

**Comment by aqw** [comment]
@bpoldrack No worries. I was just explaining, and was unaware of "data handle"'s deprecated status.

If no one has a problem, I'll close this.

---Alex

**Comment by yarikoptic** [comment]
I have tripped on it as well, forgot to complain. I don't think people associate dataset with tarball (re @hanke). I know that they know the term dataset. I know that they most likely don't know the term data handle.  If we could avoid introducing terms on the main page, would be easier to consume/digest and less scary. So I would keep this open

**Comment by yarikoptic** [comment]
This is an implementation detail AFAIK and as such not worthwhile the front page.  That sentence  would read smoother without it... what about something like

Leveraging git-annex and taking git's concept of decentralization a step further, DataLad enables scalable and version-controlled management of datasets, efficient collaboration with selective acquisition and sharing of data across dataset instances via variety of transport methods (HTTP, FTP, rsync, and more). Learn more on how DataLad relates to Git and git-annex.

**Comment by aqw** [comment]
@yarikoptic I'm ok with dropping that. Could you please reword your proposed sentence so that it doesn't list a pair of pairs? The easy fix to your sentence results in 3 confusing "and"s in a row.

DataLad enables A) the 1) [scalable] **and** 2) [version-controlled management] of datasets **and** B) efficient collaboration with selective 1) [acquisition] **and** 2) [sharing] of data across dataset instances via a variety of transport methods (HTTP, FTP, rsync, and more).

And I would recommend dropping the word "instances" from "dataset instances".

---Alex

**Comment by aqw** [comment]
@yarikoptic Ignore the previous suggestion. That paragraph has been deleted from the main page. So better wording would only be needed if the text resuscitated.

Closing as "data handles" are no longer mentioned anywhere.

---Alex
