### ISSUE TITLE
licence?

### ISSUE THREAD

**Issue by koudyk** [datalad/datalad.org#129]
I was just wondering whether you have a licence for this website code. 

I'm working to help start up something called "Open Science Office Hours". As part of our new website, we'd like to create a resource page with some filters, and we're interested in basing it on your websites "In the Wild" page. I talked to Adina about this a few months ago - it might even have been her idea, I can't remember. 

But I couldn't find a licence file in this repository. Have you chosen a copyright? 

Thanks!!

**Comment by aqw** [comment]
There is a license, it's just a bit buried. It certainly would be helpful to have a top-level license.

You can find the license page here (which covers the various assets and licenses in use):
- https://github.com/datalad/datalad.org/blob/master/content/pages/copyright.html

The rendered version is on the website:
- https://www.datalad.org/copyright.html

**Comment by koudyk** [comment]
awesome, thank you!

**Comment by aqw** [comment]
No problem! :-)
