### ISSUE TITLE
Add section / info about distribits meeting

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad.org#139]
Add section / info about distribits meeting in order to get more views

**Comment by jsheunis** [comment]
For example:

https://github.com/datalad/datalad.org/assets/10141237/8b702ea1-a09e-4bd0-84c7-8649b7491d28

**Comment by adswa** [comment]
I like the result!

**Comment by jsheunis** [comment]
Was thinking the same approach, like this on the main index page: https://github.com/datalad-handbook/book/issues/1025#issuecomment-1725723016
