### ISSUE TITLE
Come up with a better slogan

### ISSUE THREAD

**Issue by aqw** [datalad/datalad.org#14]
In the (current) tagline, the term Data Portal is used. I assume there will be resistance to this, and the term is also used for other things. Unfortunately, the initial suggestion of "Data Store" is even worse IMO, as it implies 1) cost and 2) a completely different noun.[1]

---Alex

[1] The noun I thought of is also apparently what Wikipedia's definition of a Data Store is:

> A data store is a repository for persistently storing and managing collections of data which include not just repositories like databases, but also simpler store types such as simple files, emails etc.[1]
> 
> A database is a series of bytes that is managed by a database management system (DBMS). A file is a series of bytes that is managed by a file system. Thus, any database or file is a series of bytes that, once stored, is called a data store.
> 
> MATLAB[2] and Cloud Storage systems like VMware,[3] Firefox OS[4] use datastore as a term for abstracting collections of data inside their respective applications.

**Comment by yarikoptic** [comment]
minor whinings of an obnoxious mind:  
- I dislike trailing punctuation where it is clearly implied.  E.g. in the tagline (it is well understood that it is a complete statement)... we do not have them in top menu items, do we? ;)

- I don't like leading "Providing"... would it be still english enough to make statement like 
"A data portal, a web crawler, a versioning system -- DataLad lets you have your data and control it too"  (wasn't sure where to stick "for everyone" now)

Alternative to "portal" could still be "distribution"

Started to dislike now "have your data" since kinda limits to "your" whenever it could be from others.  May be

"A data distribution, a web crawler, a versioning system -- DataLad lets you control everyone's data and code"

**Comment by aqw** [comment]
@yarikoptic Using the period is actually correct. Full sentences are always supposed to have punctuation, including in lists and headers. The menu items aren't sentences. That being said, I don't care a lot about maintaining that trailing period, as long as we are consistent.

No one cares about Google's crawler. They care about their search engine. Advertising DataLad's crawler is only something DataLad devs care about. I also don't like the word "providing."

"Data distribution" is meaningless to real people.

I agree on the problems of "your".

I am on my 200th slogan of the day. The problems with the current one are well known, but they keep getting better. Please pitch ones that are clearly better than what we have, and we'll eventually get there.

---Alex

**Comment by aqw** [comment]
A previous one that avoided the "your" problem:

> Featureful, solid, and easy to use, DataLad gives you control with data.

The "with data" feels clipped to me and the "solid" is empty to me. Michael really liked "featureful" and argued against the use of the word "open" in the tagline.

"Easy to learn" has a better pentameter to it, but "easy to use" is broader and less limiting.

---Alex

**Comment by yarikoptic** [comment]
> No one cares about Google's crawler

so ... wrong... I will not start explaining

any of those "solid", "featureful", "easy to learn" are= hollow -- they provide 0 bit of information besides the wishes of the author ;)

can't really understand what "control with data" means

**Comment by mih** [comment]
Enormous, voluptuous, easy to bend!

**Comment by aqw** [comment]
@yarikoptic When I say "no one" I'm talking about people other than non-representative people like us. And when I say "don't care", I mean they're ignorant of the problem-space/concept and it's an implementation detail to them. Thus, unimportant.

Ask any scientist in our institute about Google's crawler and they'll say one of their following

- their what?
- is that a new service/product?
- oh, you mean their search engine? (best case scenario)
- `<blank look>`

I agree that "featureful" and "solid" are empty. But "easy to use" is real. As is "open/Free".

Whatever the slogan is, it should be factually correct and meaningful to a close reading. BUT, the primary job of the slogan is not tight information. It's an emotion. People (again, using "people" in the sense of "audience") don't think at banners; they feel. They'll use words to help them feel, but it's about emotion up there. Trust, good, professional, clean, worth using, helps me, data, technical yet approachable, etc.

In the first 5 seconds, you aren't educating users, but that's the first threshold where we keep 'em or lose 'em. /After/ that, we educate them and try to keep them past that 30 second threshold. Etc, etc. until we "convert" --- the goal being to download /and/ use it.

It's a process, not something combined all into one slogan.

---Alex

**Comment by yarikoptic** [comment]
For many I know "command line" implies "pain to use". So making statement which explicitly contradicts their prior is allowed only to the only one president in the world.

**Comment by aqw** [comment]
@yarikoptic Uhh... where in the slogan does it say command line?

---Alex

Do you mean "preconceptions" instead of "prior"?

**Comment by yarikoptic** [comment]
No, I mean reality and facts. They don't have to be spelled out to be true

**Comment by yarikoptic** [comment]
Btw "open/free" is a fact

**Comment by aqw** [comment]
@yarikoptic I'm going to try to steer this back on topic. My point, not so clearly made above is: it's easy to critique the words. The only way to do this via text and be productive is to pitch full ideas that we think are "better".

I'm still chewing on some phrases, but they're all coming up short so far. Hopefully one of us comes up with something soon, because @mih's favorite right now is "Hakunah Mah'data"... ;-)

---Alex

**Comment by yarikoptic** [comment]
the last one I had was

A data portal, a web crawler, a versioning system -- DataLad lets you have your data and control it too

alternatives:

A data portal, a web crawler, a versioning system -- DataLad lets you control your data together with your code

**Comment by aqw** [comment]
> A data distribution, a web crawler, a versioning system for everyone -- DataLad lets you control the data together with the code

The front half I struggle with (will digress on later), but as for the second half, how about this?

> -- DataLad gives you control over data and code together

or, closer to the original

> -- DataLad lets you control data and code together

The front half is hard for me. To my understanding, DataLad /isn't/ a "data distribution". It's a utility. 

Also to my understanding, it isn't a "web crawler". It's a crawler that can monitor specific data targets and inject them into a dataset. But it doesn't crawl the web indiscriminately looking for data to inventory and ingest (or am I wrong on this point?).

The "versioning system for everyone" doesn't have a good mouth feel to me, but I do like the content enough that the mouth-feel isn't a showstopper.

---Alex

**Comment by yarikoptic** [comment]
Data distribution because of our growing collection at http://datasets.datalad.org so principle is very similar to Linux distributions, anaconda, etc

Crawler - reasonable point... Thought to bring counter argument of https://scrapy.org but they don't call themselves a crawler... So not exactly sure atm

... Need to run, will reply edit more later

**Comment by aqw** [comment]
@yarikoptic I wasn't clear enough, my bad. I like the term "data distribution" (where "distribution" is used as a noun, not a verb). I just don't think DataLad == a data distribution. I view the data distribution as part of the DataLad project but not part of the DataLad utility. And for me that's hard to tease apart sometimes.

I need to run too. Not sure if I'll respond any more tonight my time, so no rush. ;-)

---Alex

**Comment by yarikoptic** [comment]
re distribution: website is about the project, not just a utility. We could spell out "DataLad project" in the slogan but imho not needed

another "objective" statement we could make (echoing https://github.com/datalad/datalad.org/pull/18 discussion) is to include FAIR somehow ... not sure yet

**Comment by mih** [comment]
The new site is online. I think this can be closed. Please reopen, if that is a misjudgement.
