### ISSUE TITLE
Put whoosh-based search on datasets.html once functionality lands in datalad

### ISSUE THREAD

**Issue by mih** [datalad/datalad.org#20]
PR https://github.com/datalad/datalad/pull/1630 brings new metadata search technology to datalad. Side-effect is that we can "export" the search index from http://datasets.datalad.org and provide search-as-you-type style search functionality on datalad.org. I think this would be quite nice for showing how much we got already.

**Comment by yarikoptic** [comment]
Remember that datasets.d.o is just what datalad publishes, ie then this should be done within datalad code itself
Also it already has search as you type, just non recursive, ie only across datasets currently listed.

**Comment by mih** [comment]
Sure. That is what is the purpose of that PR. Also, I was talking about search as you type across all metadata, regardless of datasets and their actual availability or files or whatever.

**Comment by yarikoptic** [comment]
not sure how feasible could that be given that all interactions are client-side in our web ui design (there is no server support)

**Comment by yarikoptic** [comment]
whoosh based search landed, but not actively used AFAIK and not default, and unlikely datasets.org itself would expose it.  datalad-registry might eventually provide search, but unlikely to be whoosh based  anyways.
