### ISSUE TITLE
publishing rules require root login, would remove _files, etc

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#21]
there was substantial refactoring of Makefile hardcoding settings which imho should be up to `~/.ssh/config` settings instead.  Makefile should just know "whereto".  The rest (specifics of the ssh access) should be within ~/.ssh/config since they might vary across ppl/networks/situations.
Also I feel real unease with any automated action accessing critical servers as `root` -- was there a real demand for that?
It is somewhat of a convention now that we have "free floating" _files on our projects' websites (to just host some supplemental materials outside of VCS/generation)... so they **must not** be removed and if hosting is moved, should move along.

**Comment by aqw** [comment]
@yarikoptic The `root` is a placeholder. No one is actually connecting as that.

The Makefile was updated this afternoon to no longer require that the SSH_USER param be set. Please pull and it will work just fine.

---Alex

**Comment by aqw** [comment]
Or rather, since datalad has a culture of leaving issues open: reopeneing

@yarikoptic Please close this when you ack that you've opened a non-issue

---Alex

**Comment by aqw** [comment]
@yarikoptic Hmm my bad. I could have sworn I pushed it. As in, certain enough that now I'm trying to think of what different repo I pushed...

In any case. Fix already done; it's just on my comp at work; and I'm currently doing what my soul desperately needs: alcohol and rest. I was not built for back-to-back 80 hour weeks.

I'll reply to any of your other issues, etc tomorrow.

---Alex

**Comment by yarikoptic** [comment]
sorry -- I cannot push for you from your comp at work, thus assigning back

**Comment by yarikoptic** [comment]
enjoy C₂H₅OH -- I will catch up with you on that in a few hours ;)
