### ISSUE TITLE
Improve our screencast/asciinemas "presentation"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#23]
Since the idea is to not have duplicate presence at asciinema.org website, it would be nice if our "version" of those was more featureful

- [x] would be nice if some background/thumbnail (e.g. probably something around 3 sec offset from the beginning should work) was there instead of black rectangle as it is currently is. **Done in https://github.com/datalad/datalad.org/pull/26**
- [ ] need to allow some scaling, either via dedicated buttons (e.g. `80x24`, `120x36`) or automagically by desktop-vs-mobile rendering.  IMHO it is somewhat critical so visitors do not feel crippled while trying to unwrap all very long lines spit out by datalad logs/output .  We could easily achieve probably by using the same mechanism as asciinema allowing to specify terminal size: https://asciinema.org/a/134921?cols=120&rows=36 .  **Was done and then reverted for now in #26**
- [ ] great to have "documented and ready to use" script renderings of the casts, but I find them too big to just quickly overview commands.  For that I find a rendered "list of commands" with timing and urls to their help to come really handy, see above aciinema for an example.  Knowing timing helps to assess when running a command either it is stuck or indeed just should take long time.  They are useful to plan presentation/live demos (e.g. if I know that next command will take a while I better start it while still talking), etc. Also would be nice to complement with "full run time" showing total amount of time to give full estimate on how much of wall time this demo would take.  `cast2asciinema` script could be easily adjusted to generate .rst or anything else.  Eventually we might even extend with that "narrated" version Michael originally worked out.  Example of the .cmds rendered within asciinema description is https://asciinema.org/a/134832

**Comment by yarikoptic** [comment]
note regarding size:  blind attempt to widen screencasts in our features.html 
```
-    <asciinema-player src="/asciicast/basic_search.json" cols="80" rows="24"></asciinema-player>
+    <asciinema-player src="/asciicast/basic_search.json" cols="120" rows="24"></asciinema-player>
```
resulted in a bigger box but text still gets wrapped at 80, unlike what happens while rendering online:
![screenshot](http://www.onerussian.com/tmp/gkrellShoot_08-25-17_153336.png) so not yet sure how to make it happen (may be website uses different/updated player JS -- didn't check yet)

**Comment by aqw** [comment]
@yarikoptic So... you decided to ignore my statement before that making the width dynamic was a rabbit hole, and then just provide a patch doing the easy part, not testing it, and ignoring all the fallout?

That's just not a good use of your time, nor mine, and shows you don't understand the problem space.

Please fix this issues you've already identified, and then the rest you havn't found yet.

---Alex

**Comment by aqw** [comment]
@yarikoptic I poked a bit at your second point (variable width) but became less enthused about the implications. Please see #26 for my findings with this.

The third task (`.cmd` files), I'm still just not "sold" on it. My three main issues are:
* I don't see the value the timing adds; the 'cast already gives a good feel of that
* Where to visually put the link to the .cmd file so it's pretty and doesn't create confusion
  * I already dislike the placement, wording, and visual presentation of the "Get the script for this demo" link I made. I think the easy choice of duplicating that would just double the "ugh" ;-)
* the wording for the the link to the `.cmd` file (and likely change `.sh` link text too) so it's immediately clear to the user the discrete and tangible value each of these two (`.cmd` and `.sh`) resources provide

Perhaps if you/we can come up with a clear answer to the last point, it'll help me also understand the value and will bring clarity to exactly which content should or shouldn't be in that file.

I do see value in the linking to the relevant documentation. It's convenient. Not critical IMO, but convenient. I think the word "help" is a bit misleading (not too bad, just not quite 100% on-the-nose); perhaps "docs" or "more info"?

Thoughts?

---Alex

**Comment by mih** [comment]
The new site is online. I think this can be closed. Please reopen, if that is a misjudgement.
