### ISSUE TITLE
[wishlist] automate publishing of the website (using travis/circle/cron/whatever)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#25]
would be cool given that now there is more than 1 person working on the website

**Comment by aqw** [comment]
@yarikoptic If someone writes the patch, and can `git push`, I'm pretty sure they can `make rsync_upload`. This feels like automation for the sake of it rather than solving a pain-point.

**Comment by yarikoptic** [comment]
Please just trust me on this that it (automation) is has an outstanding amount of advantages here.  If you really need -- I could elaborate on advantages but I hope it would not be necessary.

**Comment by aqw** [comment]
Then may I recommend a local cron-job. As I'm not keen on having a remote private key for updating the website.

---Alex

**Comment by yarikoptic** [comment]
yeap, cron job is another way - -that is how http://neuro.debian.net gets updated... 

cons 
- delay, unless pulling frequently
- "avoids" complete specification of the environment to build (e.g. like if using travis/circle/etc) so is subject to experience side-effects of the system-upgrades, etc.  Also then at times hard to establish another build environment which produces the same result (took me a while to figure out why that bloody benchmark page didn't rebuild last time -- I didn't even notice... was missing nodejs).

FWIW credentials could be dedicated for that particular act (uploading, no tty, only one command to run or smth like that, access restricted by IPs) and configured accordingly. Secret key obviously would be encrypted so public wouldn't know.

**Comment by aqw** [comment]
@yarikoptic The secret key was my biggest concern. Not sure how we inject a private key into a dynamically created build environment defined by an open source script. But obviously you've done it, so let's do it.

Let's avoid cron, and do the full monty.

---Alex

**Comment by yarikoptic** [comment]
if we go with Travis -- here is howto https://docs.travis-ci.com/user/encryption-keys/
I have used it at some point within datalad's .travis.yml for providing some S3 credentials

**Comment by aqw** [comment]
Done along with #43 :-D
