### ISSUE TITLE
Team (or People) page?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#29]
To acknowledge everyone (current and past) on the team?

**Comment by mih** [comment]
For now, I think this would best fit on the about page, in/before/after the "from the makers of" section. Once the list get's too long, we could move it.

**Comment by yarikoptic** [comment]
I will provide photos later (should be in pymvpa repo, some are at http://centerforopenneuroscience.org/whoweare), but we should also list past ones

- Jason Gors
- Gergana Alteva
- Debanjum Solanky (he shared no photo, github avatar would work)

**Comment by yarikoptic** [comment]
@aqw what do you think?

**Comment by aqw** [comment]
@yarikoptic I don't have any ideas for this. I think it's a hard list to build for such a distributed project. And it's a good thing if it becomes even more distributed. I think a list/page kinda encourages implicitly an exclusive core of maintainers.

IMO, it's an anti-feature, and the content is best served via GitHub contributors and the info currently on the About page.

Just my 2c.

---Alex

**Comment by yarikoptic** [comment]
ah right -- we have some list buried somewhere in about. solved, unless you think it could be improved/made more fun (than just a boring list of names).  I personally  find it actually useful and also cute whenever there are faces to assign to a project, instead of making it a "thing" without a face with just some humans flowing through it. but whatever, my 1c
