### ISSUE TITLE
would not hurt to try using  travis for QA

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#3]
or may be even selenium tests/sauce lab

**Comment by Alexqw** [comment]
@yarikoptic for QA of what? To ensure the build passes? I'm genuinely curious.

---Alex

**Comment by yarikoptic** [comment]
yes, that build passes, that carousel spins, that links aren't dead, that twitter frame shows the recent news, etc

**Comment by aqw** [comment]
Closing, as I don't see this happening anytime soon nor do I think this site would greatly benefit.

Feel free to reopen if you see a clear need and/or intend to implement it.

---Alex

**Comment by yarikoptic** [comment]
yes, for build process... e.g. recently the page with file systems benchmarks just disappeared.  may be with simpler, just HTML+CSS (without much of templating/JS) it wouldn't be needed.  If notable amount of JS would come to play -- question of automatic QA would come back
