### ISSUE TITLE
Point to https://github.com/datalad/faq 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#30]
Awhile back created that repo to absorb questions people might have.  We haven't anyhow advocated it so sure thing noone really asked (besides Satra who suggested this idea).  I think such FAQ repository is a good way to get/answer generic questions, and we should use it.  But we should make it visible

**Comment by aqw** [comment]
@yarikoptic I think the idea is creative, but only is useful for a select audience (technical). At that audience has very little overlap with the people who find the most value in a FAQ.

To get an answer to their FAQ a user will be on datalad.org, click a link, be taken to an entire new platform that is normally used for development (now you lose 50% of those who clicked), read the README (lose 99% of those who remained), find and click the link that takes the user to the FAQ's, and have to realize the paradigm shift that the "Issues" are /actually/ questions and answers.

In my opinion, this is the kind of solution that makes the creators feel good, but it does little to consider the user and ensure they get the info they need as quickly as possible, in ways they would intuitively expect.

I am not arguing against the value of a good FAQ. But all to often the cart comes before the horse with FAQs. We should have a collection of genuine, valuable, non-artificial questions. And when we do, we won't want to hide it offsite, puting user-facing information on /yet another/ platform. It should live directly on the website, or /possibly/ on Read The Docs.

---Alex

**Comment by aqw** [comment]
Perhaps #5 is a better solution for FAQs. Thoughts?

**Comment by yarikoptic** [comment]
Yeah

**Comment by yarikoptic** [comment]
I will close that repo some time later or just direct to neurostars
