### ISSUE TITLE
Accompany each screencast with excercises

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#31]
So people could actually learn by practice

**Comment by aqw** [comment]
@yarikoptic I like the idea of making it a demo and tutorial combo. I think when that happens, we should go back to each feature having its own page. Otherwise "feature.html" will be the mother of all unwieldy pages. ;-)

---Alex

**Comment by mih** [comment]
But let's do that not in the same place that we use to advertise datalad.
Let's make a proper tutorial.

**Comment by aqw** [comment]
@mih Good point. I think the core question is: where should tutorial information go? Perhaps Read the Docs?

---Alex

**Comment by mih** [comment]
The new site is online. I think this can be closed. Please reopen, if that is a misjudgement. All srceencasts are gone.
