### ISSUE TITLE
Add custom 404 page

### ISSUE THREAD

**Issue by aqw** [datalad/datalad.org#33]
At very least it should allow users to easily flow back to the site. Even better if it's somewhat amusing or insightful.

**Comment by jsheunis** [comment]
This is still true after the revamped website launch, i.e. we still need a custom 404 page.

**Comment by aqw** [comment]
I've been tossing around the following for quite a few years:

"A 404 is like an empty box of chocolates. Nothing is all you're gonna get." And overlaid on an empty box of chocolates (because, you know, why be creative when you can be literal ;-).

Alternatively, some form of 404 haiku. The nature reference should be easy with "Forrest".

Or go super sentimental with a picture of Jenny's tree. Just because you can't find something doesn't mean it's lost. (How many 404s make you want to cry?)

**Comment by aqw** [comment]
Hah. And those are my ideas for the studyforrest.org website's non-existent 404. ;-P 

And I didn't even have an issue open for it. I have now rectified that: https://github.com/psychoinformatics-de/studyforrest-www/issues/58

**Comment by aqw** [comment]
> This is still true after the revamped website launch, i.e. we still need a custom 404 page.

Hmmm... maybe a JavaScript implementation of pong, with a DataLad minion as the ball. ;-)

Completely overkill.

Thinking simple:
- normal DataLad branding with search form
- completely off-base: offer one from a selection of tasty recipes
- some form of hash-collision humor (can't think of anything specific)
- minion art that represents trying to get this page/data from different remotes (HTTPS, BitTorrent, stone tablet, etc); unable to find

Not loving any of these. Will continue to think...

**Comment by jsheunis** [comment]
Ooooh I like the pong idea!

I also like the recipe idea. We could make it personal and use recipes suggested by DataLad contributors (although more work).

Others:
- a minion with one eye blinking behind a magnifying glass
- a minion sticking his head (basically equivalent to his body) into a hole in the ground

**Comment by aqw** [comment]
> Ooooh I like the pong idea!

You're only encouraging my bad impulses. ;-) I can't help but now propose something a few order of magnitudes more awesome: implementation of [World of Goo](https://www.youtube.com/watch?v=L7Bk_tHtFGM) in JS or WASM with DataLad minions as the characters. Totally doable. Probably an afternoon project. ;-P

World's best 404 page. Right there.

Recruiting people and recording the minion sounds alone would be roaringly hilarious.

**Comment by jsheunis** [comment]
![img](https://i.kym-cdn.com/entries/icons/original/000/005/574/takemymoney.jpg)

**Comment by jsheunis** [comment]
We're going to have to deliberately place bad links on the website just so that people can get to the 404 page

**Comment by jsheunis** [comment]
Done in https://github.com/datalad/datalad.org/pull/123
