### ISSUE TITLE
Add reference to the youtube channel

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#37]
https://www.youtube.com/channel/UCB8-Zf7D0DSzAsREoIt0Bvw

PS we need iirc 100 subscribers to reserve a name

**Comment by yarikoptic** [comment]
@aqw what do you think? any specific good location?

**Comment by yarikoptic** [comment]
ping @aqw

**Comment by aqw** [comment]
@yarikoptic Nope. I don't have any particular good ideas. ;-)

IMO, let's just sanely iterate on the site. When I designed this site, it was done in a rush, and there's no flow nor soul to it. I keep waiting for the right feel to come to me, but it's elusive with this site, for whatever reason.

When/if it does come, I think the organization of the site will become clear and the horror (to me at least) of the landing page will be replaced.

Until then, let's just do the best we can. Approach it as the path of least surprise for the user, while also trying to control info and stim overload for users, allowing their attention to be drawn to that which we find most important. And removing anything that's distracting.

Any change that keeps those in mind, is pretty much an automatic LGTM from me. :-)

---Alex
