### ISSUE TITLE
Additional page with asciinemas

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#38]
Features page serves us a tutorial and eventually wouldn't/shouldn't be used for all demos. We need additional page with more demos, which we could possibly reference from features of someone wants more examples on a specific topic

**Comment by mih** [comment]
That is one way to see it. Another way is that the current feature page is a mere concatenation of what was originally conceived as separate feature pages. Given that we have accumulated a good number of demos already, I will revert that back to what it was before. The main features page could then grow into something that is more than a list of links -- over time...
