### ISSUE TITLE
Scheme descriptions are incomplete

### ISSUE THREAD

**Issue by stefanv** [datalad/datalad.org#39]
http://datalad.org/get_datalad.html

Schemes listed are: `{ publish, metadata, tests, crawl }`.  In the description, `publish` and `metadata` are missing.

An extra scheme, `full`, that is not listed is described.

**Comment by yarikoptic** [comment]
@aqw?

**Comment by aqw** [comment]
@yarikoptic Michael pinged me in IM about these two issues, and if you're concerned about stepping on my toes: don't be. I'm completely cool with you making changes. But if you're swamped with stuff (he said you have an NIH meeting on Fri) then I can take care of this real quick tomorrow (as it looks to just be a quick content fix).

Let me know what you'd prefer.

---Alex

**Comment by yarikoptic** [comment]
if you could address it -- would be awesome, since I forgot the procedure to test/upload to the server.

**Comment by mih** [comment]
Before we are putting that info on the webpage may I ask why we are maintaining so many flavors/schemes and what the rules are for categorizing something as not part of the default install?

Looking into #2242 I only saw two potential reasons to not install all deps.

1. (Non-Python and/or) binary deps. For example, scrapy pulls in twisted, which has to-be-compiled extensions. This requires a complete build environment, and I can clearly see why that should be optional (didn't see another case like this besides scrapy, though)
2. Substantial change in the size of the installation. I would argue on real system that makes no difference within the range that we can manipulate. Where it would make a potential diff would be the size of a container image. In #2242 I see that the size of an absolutely barebone datalad image (that can at least show some help, and has git/annex) is 150M, an image with all bells and whistles (inlcuding scrapy/twisted and friends) is 300M -- not worth the trouble IMHO.

I would vote for not offering such a large number of schemes, but only distinguish everything vs. evrything but stuff that needs to be compiled.

**Comment by mih** [comment]
The new page uses a different approach for the installation instructions. Listing all special case flavors is now definitely beyond the scope of this page. thx!
