### ISSUE TITLE
Adjust frontpage to point to testimonials Wiki

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#41]
Now we have it https://github.com/datalad/datalad/wiki/Testimonials

**Comment by aqw** [comment]
@yarikoptic Nice that we've got some testimonials. :-)

I'd rather not send them off-site just to read them though. I recommend bringing them directly onto the main page, or setting up their own page and linking to it from the main page.

I don't think they'll all fit in a card on the front page. But that's the quick fix. Just choose 2 or 3, put 'em in a card, style the quotes, and it should be good enough for the immediate need (Friday).

Thoughts, preferences?

---Alex

**Comment by yarikoptic** [comment]
the wiki form of entry is beneficial that people could enter them by themselves without us requiring to do anything.  We cannot do it on the datalad.org since there is nothing interactive there (unless you want to enable some submission form). That is why it would be worthwhile sending them to that Testimonials page.

We could as well automatically fetch them and get a desired/representative ones to be posted on the site.

**Comment by aqw** [comment]
@yarikoptic Couldn't they do the same thing by opening an Issue on GitHub? Or just emailing us?

**Comment by mih** [comment]
I had a similar thought. If I personally want to give kudos to someones I make this either public (so it has advertisement value for the person), or private but directly to the person. I would personally not add a statement to a wiki. From the perspective of the receiver (us), what if someone writes "this is all horse shit" on the wiki. Do we then put it on the frontpage? Sensor it? Delete it? Try to argue with that person and publish the entire thread? I think testimonials should be collected by us -- with a wiki being one possible method, but not the primary location.

**Comment by yarikoptic** [comment]
I think without a negative precedence this concern is a non issue. I stole the idea full l from Mozilla/rr project. 
So unless I am proven wrong I think wiki should stay since otherwise we had no centralized location to collect them, and had no instructions to the users where to live them (besides issues but you need to sift through them). What and how is pulled to the website is up to you.

**Comment by mih** [comment]
The new site is online. I think this can be closed. Please reopen, if that is a misjudgement.
