### ISSUE TITLE
make use/publish animated datalad logo

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#47]
@mih showed a nice animated datalad logo, but I do not think it is used/published anywhere on datalad.org website.  May be it could be used instead of the static one in the left top corner, or may be make it used there only upon initial opening of the website  (for that session, so should be no need for cookie), and then getting replaced with static one?

**Comment by yarikoptic** [comment]
where was that logo again @mih? any public url?

**Comment by aqw** [comment]
@yarikoptic Just looked at the datalad/artwork repo. It seems you added it back in October:
https://github.com/datalad/artwork/tree/master/logos/animated

**Comment by mih** [comment]
It is shown at the end of the intro video, which is now at the top of the page.
