### ISSUE TITLE
Add "integrations" or "collaborations" page

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#49]
ATM DataLad is used
- by OpenNeuro - https://github.com/openneuroorg/datalad-service making all their datasets DataLad datasets available from https://github.com/openneurodatasets
- by heudiconv
- by HIRNI

and there is ongoing collaboration with
- brainlife.io

and perspective users around which might not be too shy to state it ;)

I think we need a dedicated page to list all of them.

**Comment by mih** [comment]
What is the status of the LORIS integration?

**Comment by yarikoptic** [comment]
I guess WiP and we will discover details next week

**Comment by yarikoptic** [comment]
Integrations page is now there, done in bb1c9c055beebf281d7aa1a684f9fea0fd080726
