### ISSUE TITLE
Use neurostars as main support forum

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#5]
neurostars is planing a federation of separated deployments -- would be really cool imho

**Comment by mih** [comment]
Regardless of their plans we should make this move and point to neurostars as our support forum.

FTR: Here is the link that pulls out all the posts tagged with `datalad` (just one for now):

https://neurostars.org/search?q=tags%3Adatalad

Here is the link to a "new topic" form that has the tag `datalad` prepopulated.

https://neurostars.org/new-topic?tags=datalad

I also like the guidelines that git-annex uses for its bug reports. Maybe we should prepopulate the message body with something like this:

- Please describe the problem.
- What steps will reproduce the problem?
- What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad plugin wtf`)?
- Please provide any additional information below.
- Have you had any luck using DataLad before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)

And here in URL form:

https://neurostars.org/new-topic?body=-%20Please%20describe%20the%20problem.%0A-%20What%20steps%20will%20reproduce%20the%20problem%3F%0A-%20What%20version%20of%20DataLad%20are%20you%20using%20(run%20%60datalad%20--version%60)%3F%20On%20what%20operating%20system%20(consider%20running%20%60datalad%20plugin%20wtf%60)%3F%0A-%20Please%20provide%20any%20additional%20information%20below.%0A-%20Have%20you%20had%20any%20luck%20using%20DataLad%20before%3F%20(Sometimes%20we%20get%20tired%20of%20reading%20bug%20reports%20all%20day%20and%20a%20lil'%20positive%20end%20note%20does%20wonders)

**Comment by aqw** [comment]
@mih Are there any additional threads on Neurostars that are about DataLad that we can tag? One thread just feels so... depressing.

Also, it seems that long-form URL doesn't work (at least for me, as an unauthenticated user). It redirects to https://neurostars.org/latest

I'll start putting this together; just wanted you to know my concerns.

---Alex

**Comment by mih** [comment]
@aqw AFAIK only the original poster can tag: so no other posts, for now. Depression will go away eventually ;-)

I cannot replicate your second issue. For me (unauthenticated), I get the login page, once logged in I see the prepopulated submit page.

**Comment by aqw** [comment]
@mih First point: understood. Second: I'll try authenticating and see where it goes. Perhaps it converts the GET request on the first load. I'll take a look.

---Alex

**Comment by aqw** [comment]
@mih Initial version is up; feel free to tweak the wording; I'm not in love with it and my writing juices are not flowing.

Also worth mentioning (but I didn't fix, again, because writing juices just aren't working): one bit of wording in the Neurostars template feels suboptimal:

> Have you had any luck using DataLad before?

It makes it sound like most people don't have success when using DataLad.

---Alex
