### ISSUE TITLE
Accompany each screencast with the extract of the most relevant commands

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#59]
so that they are visible on the page.

ATM it is not easy to grasp which commands are involved by just getting to the page like https://www.datalad.org/for/data-publication .

There is a static screenshot of the screencast, and then button to get a script to be opened in some editor, which in my case is actually just suggested to be saved, and then I should open it with my favorite editor, and also visually skip lots of informative comments to just get to the "pearl" of the script - the few commands which are of the primary interest in the example.  

Let's take for an example the box.com publishing example for which the full script is:
```
$> grep -v -e '^#' -e '^ *$' /tmp/boxcom.sh
set -e -u
export GIT_PAGER=cat
datalad create demo
cd demo
datalad run dd if=/dev/urandom of=big.dat bs=1M count=1
. ~/box.com_work.sh
git annex initremote box.com type=webdav url=https://dav.box.com/dav/team/project_one chunk=50mb encryption=none
datalad create-sibling-github --github-organization datalad --publish-depends box.com --access-protocol ssh exchange-demo
datalad publish --to github big.dat
git annex whereis
cd ../
datalad install -s git@github.com:datalad/exchange-demo.git fromgh
datalad siblings -d ~/fromgh enable -s box.com
cd fromgh
git remote -v
datalad get big.dat
ls -sLh big.dat
```
I think it would be useful to have an excerpt such as below posted right before or after the screencast.  We can annotate in the screencast for automated extraction, but not sure about nice formatting for the long lines, but probably could be done as well:
```shell
# Publish repository to github and data to box.com
git annex initremote box.com type=webdav \ 
   url=https://dav.box.com/dav/team/project_one \
   chunk=50mb encryption=none
datalad create-sibling-github --github-organization datalad \
   --publish-depends box.com \
   --access-protocol ssh exchange-demo
datalad publish --to github big.dat
```
If datalad commands (e.g. `create-sibling-github`) could acquire hyperlinks to the docs.datalad.org for them, would be just great!
What do you think?

**Comment by mih** [comment]
The new site is online. I think this can be closed. Please reopen, if that is a misjudgement. Screencasts are gone entirely
