### ISSUE TITLE
Offer promotional material for download

### ISSUE THREAD

**Issue by mih** [datalad/datalad.org#64]
I have been asked for something like a "DataLad-managed" badge that could be put on a poster, but it would also make sense to have this be available for github repos etc.

**Comment by aqw** [comment]
For repos etc, shields.io would be a good fit. We can contribute at https://github.com/badges/shields

For the poster, either one of those badges or the square DataLad logo makes sense to me. But I don't know what's "normal" for poster badges, so perhaps I'm missing something.

**Comment by mih** [comment]
We have a badge for datasets for a while now. Good enough it seems.
