### ISSUE TITLE
"team@datalad.org" help email not working?

### ISSUE THREAD

**Issue by mrneont** [datalad/datalad.org#65]
Hi-

I've emailed from two separate accounts to the email "team@datalad.org", which is listed here:
https://www.datalad.org/development.html
... and both times, I receive bounceback messages after a couple days:
**The following message to <team@datalad.org> was undeliverable.
The reason for the problem:
5.4.7 - Delivery expired (message too old) 'timeout'**

Is that email not working, since the same thing is happening from separate accounts of mine?

--pt

**Comment by yarikoptic** [comment]
thanks for the buzz! it seems that the elderly server is down. I will attend to the patient tomorrow when get to work.
meanwhile you can email me and @mih directly or publicly here or neurostars.org

**Comment by mrneont** [comment]
Thanks, @yarikoptic , I will do that.

I actually had already asked a related question at neurostars.org:
https://neurostars.org/t/intro-to-datalad-searching-through-file-jsons-sidecars/4709
... but the email relates to datalad examples and larger help issues, as well.  

It is a pretty long query I had emailed-- basically, listing a few online datalad examples weren't working for me-- and I don't know if it lends itself to being an "issue".

**Comment by yarikoptic** [comment]
server was kicked (failed to find one of its elderly IDE drives upon initial boot) and is up now. Thanks again for the report... will try to get to the question/answering later today
