### ISSUE TITLE
apt-get datalad gets version 11

### ISSUE THREAD

**Issue by dkp** [datalad/datalad.org#71]
Could you update the apt-get package?  It is difficult to teach datalad when I cannot easily get an up-to-date package ; (

**Comment by yarikoptic** [comment]
well, that is what your debian or ubuntu release has and there is no way to change that.  For backports of recent datalad release use neurodebian -- see http://neuro.debian.net/pkgs/datalad.html .  That is what https://www.datalad.org/get_datalad.html#neuro-debian-ubuntu-and-similar-systems recommends and we should just point that page to http://handbook.datalad.org/en/latest/intro/installation.html which would contain more up to date and complete instructions

**Comment by dkp** [comment]
Thanks for your prompt feedback. My use case involved provisioning google cloud shell with Datalad. Even after adding the Neurodebian repository,...

sudo wget -O /etc/apt/sources.list.d/neurodebian.sources.list http://neuro.debian.net/lists/buster.us-nh.full

sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80   0xA5D32F012649A5A9

apt-get update

...it was not possible to do a Datalad install.  The cloudshell VM found Datalad 0.14, but the install could not finish, because of something called "popularity contest" that caused it to hang ; (.  This was despite using the most automated quiet install we could identify:

sudo DEBIAN_FRONTEND=noninteractive apt-get -y install datalad

(all of this in green has to go into a .customize_environment file for google cloud shell)

Interestingly, this automated install (DEBIAN_FRONTEND=noninteractive apt-get -y install datalad) did work correctly on a test Debian buster 10 machine where we ran as root, so I guess I have to blame Google Cloud Shell....but I thought you should know.

In the end, I used the miniconda route, and that seems to be working nicely.

Is there any possibility that you will offer Datalad in a Docker container in the future?
I like the singularity container, but could not find a comparable Docker container.

Thanks for your time.  I think Datalad is really exciting and I follow your progress.

-Dianne

Dianne Patterson, Ph.D
Speech, Language and Hearing Sciences, Room 314
dkp@arizona.edu
________________________________
