### ISSUE TITLE
deprecate/remove asciinema casts in favor of referencing handbook

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#75]
Should close #23 #31 #45 #46 #59

Should just lead to http://handbook.datalad.org/en/latest/usecases/intro.html  (@adswa @mih -- is there a "shortcut/permalink" url? related https://github.com/datalad-handbook/book/issues/696)

**Comment by mih** [comment]
The new site is online. I think this can be closed. Please reopen, if that is a misjudgement.
