### ISSUE TITLE
Replace/upgrade www.datalad.org

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad.org#77]
The current page is outdated and could do with a revamp. Keep the new page lean, possibly single page.

Ideas:

- Remove unnecessary content
- Add pointers to:
   - the handbook
   - datasets.datalad.org
   - github.com/datalad/datalad
   - the publications
   - "try on binder" demo
- the integrations page's content is important, but not its composition
- there should be room for a future pointer to a greater dataset catalog
- a comprehensive list of support/interoperable services

Comments welcome.

**Comment by yarikoptic** [comment]
Knowing what content is considered unnecessary could help to focus the replacement... May be we could even just have a single page site there since majority of the content is text and anything major worked be just pointers

**Comment by jsheunis** [comment]
If we stick with Pelican, it might be useful to see if there are themes we like: https://github.com/getpelican/pelican-themes (demos here: http://www.pelicanthemes.com/).

OTOH, if we will only go with a one-or-two page site, we might also stick with standalone html without needing to build multiple content pages in MD, RST, or whatever else Pelican has support for.

I'm not entirely sure which valuable aspects of a framework like pelican we will miss out on if we go with the second option.

@aqw I'm interested in hearing if you have an opinion on this.

**Comment by jsheunis** [comment]
Thanks, seems sensible.

**Comment by jsheunis** [comment]
I'm collating a list of DataLad extensions/integrations/uses for the website upgrade. The idea is to present them in a visual way as so-called cards, each with standard properties like a logo, name, short description, tags and links. Then we can build in some nice searching/filtering/ordering functionality.

I've gotten most of the existing information from the current website and have started filling in the details here: https://docs.google.com/spreadsheets/d/1ElQpVFXb-eRguupAkG6pl48o8QBQNK1qw-18linqCLA/edit?usp=sharing

I'd like some help to make this list as complete and comprehensive as is currently sensible. Mainly:
- if you know of any other extensions/integrations that should be on the list, please add them
- if you have the knack for shortening a description while keeping the essence, please give those a go
- if you have ideas for tags to add to the items, please do so
- if you think some items do not fit in the list, please make a comment to that extent

**Comment by jsheunis** [comment]
The latest version of the website is now available in the `stephan-revamp` branch: https://github.com/datalad/datalad.org/tree/stephan-revamp

And the demo version is published here: https://jsheunis.github.io/wwwdataladorg/

I will continue creating issues for the remaining tasks before we can deploy the new site, and tag people where I think their input will be useful.

**Comment by aqw** [comment]
Closed by #100 !!
