### ISSUE TITLE
Please kill datalad/pelican-bootstrap3

### ISSUE THREAD

**Issue by aqw** [datalad/datalad.org#8]
@yarikoptic @mih datalad/pelican-bootstrap3 is no longer needed.

---Alex

**Comment by mih** [comment]
Let's wait a bit with that. We still have that annex benchmarking article to go somewhere. Once we figured that one out the old page is truly obsolete.

**Comment by aqw** [comment]
@yarikoptic Is there any other unique content hosted on old.datalad.org? I can easily just grab [benchmarking page ](http://old.datalad.org/test_fs_analysis.html) as is, and have pelican copy it into the website statically.

That, or it can be turned into a proper page in the new theme. I don't remember what the blocker was for that though.

---Alex

**Comment by yarikoptic** [comment]
I do not think there was anything other valuable.  The whole or majority of that page is coming from an ipython notebook IIRC using some plugin to render it into pelican.  But since one time show, indeed might be easiest just to get a static copy and be done

**Comment by aqw** [comment]
@yarikoptic Cool. Then I will do so tomorrow. And then both old.datalad.org and datalad/pelican-bootstrap3 can be retired. :-)

---Alex

**Comment by aqw** [comment]
Ok. I went a little overboard, and ended up converting the page to use the new site theme. Since you said it likely won't be re-generated, I took the time to clean up the generated HTML so it's readable by humans too. ;-)

While I was at it, I extracted the images (so they're no longer BASE64 encoded in the webpage), gave them a background (so their text is legible in webkit and blink browsers), and optimized them to reduce payload size.

Let me know if you find any problems I introduced, but I think it's all good.

And then, I think datalad/pelican-bootstrap3 can be retired. :-)

---Alex

**Comment by yarikoptic** [comment]
Thanks @aqw ! looks great.  Should we have it referenced to somewhere on the website since it is there now in a representable shape?  may be within Development page?

**Comment by aqw** [comment]
@yarikoptic Yeah, it would make sense to link to it /somewhere/. ;-)

I agree, the Development page makes most sense. Though that page, in general, needs to be rethought so that it more intuitively conveys the info we wish to share. Another link on it won't hurt though. :-)

As an aside, I'm curious how the FS tests would look using ZoL 0.7.x. There were huge performance gains (especially for metadata) with the 0.6->0.7 upgrade. "Someday" we should run those tests again. :-)

---Alex

**Comment by yarikoptic** [comment]
Yeah and In principle it should be possible without major pains. I would just need to buy a few new drives to test on and be careful to not kill existing drives with data ;-) all the scripts are here I think https://github.com/datalad/benchmarking

**Comment by aqw** [comment]
@yarikoptic The link has been added to the dev page. So all is well now. Thanks for the link to the benchmarking repo. I've spent to morning distracting myself, with assorted cleanups in some of the scripts. A PR will follow once they begin to make sense. :-)

**Comment by yarikoptic** [comment]
Ouch... Now your are doomed to run it! ;-)

**Comment by aqw** [comment]
@yarikoptic Haha. I am ok with that. But I would need some drives... ;-)

**Comment by aqw** [comment]
@yarikoptic Also, as a followup, any chance of retiring datalad/pelican-bootstrap3 and old.datalad.org so we can close this issue? I don't have cool-kid-admin privileges for the repo. ;-)

---Alex

**Comment by yarikoptic** [comment]
> retiring datalad/pelican-bootstrap3
is just a matter of git rm I believe (for .gitmodules as well) 
as for old. -- powers are of @mih

**Comment by aqw** [comment]
Sorry, I'm a bit confused. I can delete the "old" branch in this repo, and mih can retire the DNS, but the actual datalad/pelican-bootstrap3 repo, I don't have perms for. I assumed you did though.

---Alex

**Comment by mih** [comment]
Repo is gone.

**Comment by yarikoptic** [comment]
ah... it would've not hurt to keep it around "just in case" since it doesn't consume anything for us and neither is in the way of things, but that is ok

**Comment by yarikoptic** [comment]
@aqw re https://github.com/datalad/datalad.org/issues/8#issuecomment-408822974
- did I miss a PR? ;)
- would indeed be interesting to see (whenever any of us gets to it) what is the current state of affairs.  BTRFS so far performed quite well for me.  But reports like https://www.phoronix.com/scan.php?page=article&item=linux414-fs-compare&num=2 (for other types of load though) suggest that may be performances of other systems changed meanwhile ;)

**Comment by aqw** [comment]
@yarikoptic No PR yet, as the changes just kept going, and I didn't really have a setup to test them on. Not sure if you want expansive rewriting of the scripts with no testing. :-/

BTRFS has some cool potential, but the oops with their parity RAID levels left a pretty bad taste in my mouth. My "great hope for the future" is DragonflyBSD's Hammer2, although it's doubtful that it will ever be ported.
