### ISSUE TITLE
Proof reading and general feedback required

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad.org#83]
@datalad/developers 

It would be good to get any form of feedback on the current site revamp: https://jsheunis.github.io/wwwdataladorg/. 

General things to look out for:
- issues/bugs
- suggested improvements of content / figures / layout / functionality
- typos
- rephrasing or renaming sections
- feature requests

**Specific things:**
- Please suggest any other extensions / integrations / articles that should be included in the "DataLad in the Wild" section. NB: I will still include the articles listed on the current datalad.org site.
- Please check if you agree with the tags added to these items (NB: the main `extension`, `integration` and `article` tags must still be added): https://github.com/datalad/datalad.org/blob/stephan-revamp/content/static/integrations.json

Before you create an issue, just check the [revamp](https://github.com/datalad/datalad.org/issues?q=is%3Aissue+is%3Aopen+label%3Arevamp) tag in case the issue already exists.

Thanks!

**Comment by yarikoptic** [comment]
some observations from a narrow view (not really mobile AFAIK)

top of the website looks odd -- has some non actionable oval:
![image](https://user-images.githubusercontent.com/39889/140232712-f0e18eb4-24e0-4b4d-aaa1-185176e0985b.png)

and here you can see some odd indentation of that itemized list.

also those "marks" at the bottom:
- lots of space around them. not sure if improves anything?
- might be worth making them actionable to lead to `#fragment` for the next section/slide?  and then they could follow right after the text (if empty space is desired) to scroll to the next one

What is "TemplateFlow" integration?

Integration icons I guess will gain some urls behind them?

some images do have some sticking out line, which kinda creates a margin for the text (like in above) but most don't have that and then image sticks too close IMHO to the text e.g.
![image](https://user-images.githubusercontent.com/39889/140233485-7f0fc0d2-e90b-4218-810e-793ac67a038e.png)

in the bottom I get the acknowledgement in presumably (not really) scrolable text box 

![image](https://user-images.githubusercontent.com/39889/140233574-14fe620b-edd4-47f4-b84c-cc533fa96c41.png)

I guess scrollbars should just be disabled for it altogether

**Comment by jsheunis** [comment]
Thanks @yarikoptic! Is this with Chromium? Looks similar to what @adswa saw. I will create a separate issue to address Chromium-related styling bugs.

The non-actionable oval in the navbar is a WIP with #81.

**Comment by jsheunis** [comment]
Templateflow: https://www.templateflow.org/

If you hover over the "integration" cards, they give a short description of the integration and links to websites, docs, etc

**Comment by mih** [comment]
The new site is online. I think this can be closed. Please reopen, if that is a misjudgement.
