### ISSUE TITLE
Thorough testing of the new site in multiple browsers

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad.org#84]
The site was tested during development using Chrome and Firefox. Safari (and other browsers?) still needs some attention.

**Comment by adswa** [comment]
I can confirm that everything looked good under Firefox 91.2.0esr.

Chromium Version 90.0.4430.212 (Developer Build) had these light scrollbars in the footer
![Screenshot from 2021-11-04 08-09-59](https://user-images.githubusercontent.com/29738718/140272067-4cbb8d47-5025-4366-8a00-1fe2b24e7966.png)
and the icons in the header appear to be shifted more to the left than on firefox
![Screenshot from 2021-11-04 08-11-15](https://user-images.githubusercontent.com/29738718/140272157-5b1eb2e4-679f-4bfc-bdd8-caa48a229467.png)
(here is Firefox for comparison)
![Screenshot from 2021-11-04 08-11-52](https://user-images.githubusercontent.com/29738718/140272202-ed7f8d61-b77a-43bf-8b99-9e334e5fc3e2.png)

**Comment by jsheunis** [comment]
Thanks!

**Comment by aqw** [comment]
I can confirm that all of the above bugs (and many more) have been fixed.

There are many smaller ones lurking. But the site has been tested on multiple browsers, devices, and OSs. I feel comfortable closing this now. Please open specific issues for any future bugs encountered.
