### ISSUE TITLE
Minor language nitpicks

### ISSUE THREAD

**Issue by adswa** [datalad/datalad.org#85]
A few language nitpicks I stumbled across while reading through the webpage:

![Screenshot from 2021-11-04 07-26-18](https://user-images.githubusercontent.com/29738718/140267866-e3b751cb-aa54-4132-8c98-1ff1abf85fad.png)

I guess it should be "Capture full provenance record_s_"? The first bullet point ("View data change history") is somewhat peculiar, but I can't really verbalize what I find odd. I think its that the sentence has multiple interpretations? (data changing the history, "data-change"-history) 

![Screenshot from 2021-11-04 07-31-42](https://user-images.githubusercontent.com/29738718/140268269-7d065114-1a0b-49f3-b1fd-b04454d6df5b.png)

I think this text block could connect a bit better to its heading ("Create structure"), like the first text block. I'm struggling to come up with something nice, but maybe something along the lines of this would work? (I basically tried to smuggle the words "create structure" inside) 

> A DataLad dataset is a directory with files, managed by DataLad. You can link other datasets, known as subdatasets, and perform commands recursively across an arbitrarily deep hierarchy of datasets - thus creating structure while maintaining advanced provenance capture abilities, versioning, and actionable file retrieval.

![Screenshot from 2021-11-04 07-52-56](https://user-images.githubusercontent.com/29738718/140270170-31e4774e-39a3-4494-ac11-18add807c632.png)

maybe not "clone online datasets" but "clone _other_ datasets"? (or similar, because they don't need to be online). And maybe not "push changes to a remote store" but "push changes to remote _places_"? (or similar, just to not make the impression it needs to be a RIA store or something special)

![Screenshot from 2021-11-04 07-55-57](https://user-images.githubusercontent.com/29738718/140270479-583f30ab-d590-4d8a-a12a-4307cf21a140.png)

Other headings only capitalized the first word plus "DataLad".

![Screenshot from 2021-11-04 07-58-50](https://user-images.githubusercontent.com/29738718/140270781-3d5fa4b1-2b96-4826-8ee6-4fa064c86a56.png)

Maybe end the last sentence with a ":" to connect it to the icons below?

![Screenshot from 2021-11-04 07-59-53](https://user-images.githubusercontent.com/29738718/140270879-74cc6763-313c-4dfa-9a38-20b73cacf57c.png)

"creating" instead of "logging" issues, maybe?

![Screenshot from 2021-11-04 08-01-05](https://user-images.githubusercontent.com/29738718/140271034-4f7f0f79-04f6-4ddb-a25a-e4bb20c51090.png)

What do you mean with "file nesting"?

And finally, I think you linked to DataLad's Youtube channel via the 'old' URL (https://www.youtube.com/channel/UCB8-Zf7D0DSzAsREoIt0Bvw), I think https://www.youtube.com/datalad works just as well

**Comment by jsheunis** [comment]
Thanks, great points!

**Comment by jsheunis** [comment]
Fixed in 1d3d9ad655e29d00b3eb9881e8e345dcea5a96b5
