### ISSUE TITLE
Suggestions for integrations

### ISSUE THREAD

**Issue by adswa** [datalad/datalad.org#86]
More integrations could be:
- Other git repo hosting services: Bitbucket, Gitea, Gogs
- Other datalad extensions: datalda-container

Text suggestions for yet missing text blocks:
- Git: "DataLad datasets are Git repositories - anything compatible with Git also works for your datasets". Maybe link to git-scm.com as the homepage?
- git-annex: "DataLad datasets can have an annex, and thereby all the data versioning and transport features git-annex provides"
- xnat: "The datalad-xnat extension allows you to track and update medical image acquisitions from XNAT servers".

Logo suggestions for yet missing logos:
- HeuDiConv: Maybe the nipy logo? (https://nipy.org/img/nipy.svg)
- TemplateFlow: Maybe a T1 atlas of those featured on the template flow docs landing page? (https://www.templateflow.org/)
- DataLad MetaLad, DataLadNeuroImaging: No idea yet, but maybe its time to come up with a logo @yarikoptic @christian-monch? datalad-xnat and datalad-osf already have one :)

**Comment by jsheunis** [comment]
Updated in c3eeffb85d96ec11a8e7279955693887693acbbd
