### ISSUE TITLE
Get revamped page html and css to validate

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad.org#89]
https://validator.w3.org/nu/

**Comment by jsheunis** [comment]
Summary:

- 58 validation errors/warnings
- `Bad value https://matrix.to/#/#datalad:matrix.org for attribute href on element a: Illegal character in fragment: # is not allowed.` ==> not sure if we can do anything about this
- `The frameborder attribute on the iframe element is obsolete. Use CSS instead.` ==> fixed
- ` No p element in scope but a p end tag seen.` ==> validator seems to be wrong, or some syntax issue is causing it to see this as a problem, where it isn't (there is a `p` element)
- All other validation errors/warnings (~52) related to VueJS directives / tags 🙃

**Comment by aqw** [comment]
Index page validates now. Vue still shits all over the "in the wild" page.

**Comment by jsheunis** [comment]
Closing, since everything validates except for vue 🙃
