### ISSUE TITLE
pics folder -> datalad/artwork?

### ISSUE THREAD

**Issue by aqw** [datalad/datalad.org#9]
@yarikoptic I see that you added a miniature treasure-trove of demo-related images. https://github.com/datalad/datalad.org/tree/master/src/content/pics

Are these needed on the website? They're not consumed by any page.

Perhaps they're a better fit for datalad/artwork or someplace else?

I'll even move 'em for you. Just let me know where they go. ;-)

---Alex

**Comment by aqw** [comment]
@yarikoptic ping?

**Comment by yarikoptic** [comment]
feel welcomed to mv them to the artwork
