### ISSUE TITLE
code escapes the terminal 

### ISSUE THREAD

**Issue by adswa** [datalad/datalad.org#99]
When I open the website in a browser that takes up my complete screen, the code examples escape its terminal under Firefox and Chrome. Its fine when my browser takes up half the size of my screen though.

![Peek 2021-11-26 09-31](https://user-images.githubusercontent.com/29738718/143551162-db980ce9-6e2c-4652-989d-1ac1b7e6fc9d.gif)

**Comment by aqw** [comment]
Can you reproduce this? We made a schload of changes today. I would not be surprised if this was fixed accidentally.

If you still can tickle the problem, can you share what combination triggers it? I wasn't able to do so.

**Comment by adswa** [comment]
No, its fixed, was about to close it :)
